### ISSUE TITLE
Sidebar rebrushing.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#13] opened 2015-04-03 12:01 UTC
Featuring:
 - better organisation;
 - new symbolic icons;
 - ability to hide main categories (that's what the triangles do);

What do you think?
![screenshot from 2015-04-03 14 54 32](https://cloud.githubusercontent.com/assets/1658870/6981869/bcd04e02-da11-11e4-81eb-2cd7d973e9f5.png)

**Comment by fossfreedom** [comment] 2015-04-03 14:07
I'll have a look a little later.  However I dont think there is a method in the Rhythmbox API to differentiate between local sources and online sources.

Thus - custom sources from third-parties will not be displayed if we "hard-code" the sources in each area.  I suppose there could be an "other" category for these.

We should consider throwing this upstream to see what Jonathan makes of the suggestions.

If we are considering keeping this local - yes I think its possible to implement as described - wouldnt be a quick implementation - may take a week or two to get something usable.

**Comment by me4oslav** [comment] 2015-04-03 20:15
I would prefer upstream implementation, but last time we talked with Jonathan he said something like that my radio symbolic (which is ... a radio) doesn't make sense for a radio. It is hard to imagine my face after reading this. :P

**Comment by fossfreedom** [comment] 2015-04-09 12:41
The actual implementation of the visual design is straight-forward.  Just need to "borrow" the idea already implemented in the coverart-browser toggle where we swap between list view and cover view.

The bit making me very nervous is the hooks throughout rhythmbox to create playlists for various selections.  When you create a playlist from a source, rhythmbox use the current sidebar to first ask the user to give the playlist a name - right click a track and create a playlist to see what I mean.

From the Rhythmbox API there doesnt appear to be a method to intercept this call - so a user saying "create a playlist" will be left waiting to provide input on a sidebar that is visually hidden because the sidebar has visually replaced by the new design.

I need to have a closer look at GTK and see if there is a "pre-create" type signal on a Gtk.TreeModel that could be used to intercept the call.

Alternatively look at how to force the name of the playlist to be set - use the current Rhythmbox API to recognise that a new playlist has been created ... and then display this in our new sidebar in "edit mode" ... yes it all sounds very convoluted.

I'll have a look at this in the next few days to see if the above is an absolute showstopper - or not.

**Comment by fossfreedom** [comment] 2015-04-15 23:19
ok - making progress on this one.

The commit above is work-in-progress.  It currently shows the refreshed sidebar together with the old-sidebar in the same pane.

Completed so far:

1. split the sources between local/online/other & playlists
2. show the new icons for the sources
3. respond to new sources being added via "plugins"
4. respond to sources being removed via "plugins"
5. respond to new playlists being created
6. respond to playlists being deleted
7. on click of a source - correctly display that source

Still to-do:

1. add the +-(eject) buttons
2. Hook up editing of playlist names
3. Hook up creating and editing new playlist names

**Comment by me4oslav** [comment] 2015-04-16 09:44
Also to do
  -  make the radio symbolic coloured by the GTK theme;
  -  make the playlists use the icons;
  -  make the sidebar use the same sidebar widget as in other Gnome apps.
![screenshot from 2015-04-16 12 44 15](https://cloud.githubusercontent.com/assets/1658870/7178297/57b0718a-e436-11e4-8c24-8663679d88f9.png)

**Comment by fossfreedom** [comment] 2015-04-16 11:10
There looks to be something wrong with the radio symbolic - it is the same code being used for all the icons.  Can you look at this please.

Playlists will also need your help.  Remember - the My Top Rated and Recently Added Playlists are just "Automatic Playlists" - you have the ability to delete these  as well as creating new automatic playlists.

As Jonathan has said - playlists are only divided between automatic playlists and static playlists.   So we need generic icons for those two types.  I can hard-code the icons for those three displayed playlists if you so wish - but you need to give me the other two icons.

Nautilus doesnt use any standard widgets for the side bar - its all custom code and styling.  So that's not a good example you have given. What other Gnome apps use the "sidebar" that displays subitems like a tree?

**Comment by fossfreedom** [comment] 2015-04-16 11:16
... just had a thought -  the radio icon you gave isnt named correctly - should be "-symbolic.svg".  I'll rename this to see if this resolves this.

**Comment by me4oslav** [comment] 2015-04-16 16:20
Right, lemme have dinner and will help you.

**Comment by fossfreedom** [comment] 2015-04-16 16:35
I think that side bar you mentioned is this widget 

 - https://developer.gnome.org/gtk3/stable/GtkPlacesSidebar.html

It only can be used to display file system locations

**Comment by me4oslav** [comment] 2015-04-16 20:35
Playlists - I see. Don't you have the rest of the symbolic icons?
Radio - yes, adding a "-symbolic" suffix should do it.
Sidebar - I will check tomorrow and tell you.
Sorry for the late reply, but between work, studying and medications I have very little free time, which I spent mostly in sleeping and relaxing.

**Comment by fossfreedom** [comment] 2015-04-16 20:47
I've got the recently added and recently played.  The top rated is "starred-symbolic"

I need another icon for when a user creates  an automatic playlist.  I'm using the audio-x-playlist-symbolic icon for the static playlists

yep confirmed - both librefm and radio - adding symbolic fixes that.

Hey - take it easy! :)

**Comment by me4oslav** [comment] 2015-04-16 20:49
Will reply tomorrow.

**Comment by me4oslav** [comment] 2015-04-17 08:26
Right, compiled the latest sidebar branch and:
  -  playlists icons are not fixed;
  -  so are radio and libre.fm icons;
  -  import errors still misses an icon. It should use "dialog-error-symbolic";
  -  there is no on hover effect for the new sidebar;
  -  when an element is selected the text changes its colour to the proper one (fg_color, I believe), but the symbolic does not;
  -  the new sidebar background colour should be the same as the one on the old one;
  -  the inline toolbar with the +, - and  ^ (add, remove, eject) is missing;

I believe that's all. Tell me if you need anything more from my end.

**Comment by fossfreedom** [comment] 2015-04-17 08:45
? hover effect on the new sidebar.  What is this?

dialog-error-symbolic - RB didnt do this.  I'll raise that suggestion on the RB bugzilla but will add the icon for the new sidebar anyway.

Don't know about the colour changes - I'm not doing anything different in Gtk Treeview Cellrenderer than what is available in Gtk.   I'll have a closer look at the RB treeview implementation to see if I've missed anything.

+-^  - look above - still stuff to do.  

From you - I still need an automatic playlist icon - alternatively nominate a stock icon I should use.

**Comment by me4oslav** [comment] 2015-04-17 09:03
Look at e the current sidebar, when you hover over and element it has some effect. For example in Ozon GTK the text and the symbolic go teal. This does not happen with the current sidebar.
dialog-error-symbolic - OK.
Colour changes - OK.
+-^ - OK.
Automatic playlist icon? Aren't the playlists icons solved in the latest commit in the sidebar branch? 'Cause the look OK to me - both the icons for the three automatic playlists and the icons for the custom created ones.

**Comment by fossfreedom** [comment] 2015-04-17 09:23
Click the "+" button - you'll have an option to create a static playlist or another automatic playlist.  Choose the "new automatic playlist" option - after you fill in the dialog you'll see another playlist that looks like the my top rated/recently added/recently changed.

Click the "+" button again and create "New playlist" - you'll see the visual difference between the two types 

![Imgur](http://i.imgur.com/J2MtEpa.png)

**Comment by me4oslav** [comment] 2015-04-17 19:28
I will have a look tomorrow.

**Comment by fossfreedom** [comment] 2015-04-17 20:16
Hi - thanks for this.

Also - some HIG and style advice when you have some time.

If you have a look at gnome tree views you will see that the indentation between the first level, second level and third level is relatively large.

For the side bar you can see the the children under the header (e.g. "local collection") is indented leaving very little of the text visible for the child source (e.g. "Music").  This forces you to have a much wider sidebar - this to me doesnt look quite right.

I've been looking around but it appears that this is by design and there is very little you can do about it - i.e. you cannot really reduce the indentation because it appears this is mainly controlled by the theme being used.

Rhythmbox has a custom expander - its a little strange - you double click the header to open and close.  When you want to open - for example - lastfm to reveal its children you do so with a single click.

The expander icon you see on the right hand side of the text (like in your original drawing) is a custom cairo-drawn icon.

Now - I could also switch off the standard expander icons - I could control the expanding/collapsing myself.  For example - we could single click a header to open the child sources below it - slightly indent the children.  This will make the sidebar much more compact - visually showing much more detail.

I could also add a expander icon after any source (e.g. lastfm) that has children just like how rhythmbox does now.

What do you think about this?  I know this isnt strict Gnome - but the behaviour of the standard Gnome widget breaks the clean visual look I think you are looking for.

There are no symbolic "expand"/"collapse" icons - so if you want to go down this route - could you design a couple of icons?

**Comment by me4oslav** [comment] 2015-04-20 07:11
Right, I don't have a lot of free time, but I managed to compile the latest sidebar branch and it is so much better than before.
The only issue I noticed is that the three main categories don't save the toggle status. The player always starts with local collection expanded and online sources and playlists collapsed. It should remember which categories are left expanded and which collapsed on startup.
Here is the icon you need for automatic playlist (mimetypes/audio-x-playlist-automatic-symbolic):
https://dl.dropboxusercontent.com/u/2656555/rb-symbolic-icons.tar.gz
In the tarball just in case I fixed the "-symbolic" suffix issue. I also added a bit better last.fm symbolic (apps/lastfm-symbolic.svg).

**Comment by me4oslav** [comment] 2015-04-20 11:29
Oh and, this sidebar redesign should address issue #21, I think.

**Comment by me4oslav** [comment] 2015-04-21 06:59
I see that new icons (last.fm and the automatic playlist) are added. Nice.
Unless we've missed something what is left to do design implementation wise are the two issues I outlined above and the issue you raised a few comments above. Great job.
After the sidebar rebrushing is complete, I will either start on coverart plugin redesign or improving the categories pane.

**Comment by fossfreedom** [comment] 2015-04-21 09:28
Just a couple of stuff I need to do - test what happens when plugging in a phone - it should appear in the local section.

The stock sources such as magnatune and fmradio needs to appear in the online sources.

Will do the "remember what was open".

The "My Top Rated" to "Top Rated" - is not easy to-do. This is RB text that really should be changed in the source.  Besides the change will break any translations in this area.  We should start thinking about how to handle translations for the new text.  Will need alot of community help on this one.

**Comment by me4oslav** [comment] 2015-04-21 11:35
-  Plugged my Nexus 5 - appears in "Other sources" as "Nexus 5". Here is a screenshot:
![screenshot from 2015-04-21 14 34 43](https://cloud.githubusercontent.com/assets/1658870/7251373/91800e06-e833-11e4-87cf-5468e219a757.png)
  -  Magnatune and fmradio need fixing as you said.
  -  What was open - great to see that this will get fixed.
  -  Stings - this is why I hate papercuts. A silly bug like adding an extra not needed "my" and now an upstream patch and translation changes are needed. :(
  -  Need to find the time to look at the suggestion you outlined above, but currently publishing my first book preview to Amazon is eating my pretty much non existent free time. :P
  -  Shouldn't the sidebar get a border on the right?

**Comment by fossfreedom** [comment] 2015-04-21 23:03
ok - stuff merged with master and version number bumped

**Closed by fossfreedom** 2015-04-21 23:03 UTC
Labels: enhancement

**Comment by me4oslav** [comment] 2015-04-22 08:54
Right, but I see the issues from the latest comment are standing. Should we open a separate bug report about them?

**Comment by fossfreedom** [comment] 2015-04-22 11:27
anything extra - yes - create additional issues.

**Comment by me4oslav** [comment] 2015-04-22 14:39
Done.
The new issues are: #30 , #31 and #32.
