### ISSUE TITLE
Random segmentation faults when enabling this plugin

### ISSUE THREAD

**Issue by fin-ger** [fossfreedom/alternative-toolbar#82] opened 2016-02-14 01:20 UTC
When enabling this plug-in rhythmbox (3.2.1) crashes randomly when changing the song or browsing through the library. The command line does not give any further information, it just says `segmentation fault`. Without the plug-in enabled I didn't run into any issues. Any suggestions on how to address this problem?
##

**Comment by fossfreedom** [comment] 2016-02-14 09:25
Thanks for raising the issue.

Suggest run rhythmbox in debug mode

  rhythmbox -d

Once we've narrowed down the issue, I'll ask you to install the rhythmbox debug symbols package for your distro and then run gdb to get a backtrace.  This will pinpoint where the crash actually occurs.

The last dozen or so lines often gives a hint as to what the issue is.

What is your linux variant?   Anything special about your setup e.g. new version of python?  Upgraded GTK stack from what the distro gave you?

**Comment by fossfreedom** [comment] 2016-02-14 10:14
BTW - when testing please make sure no other plugins are enabled at the same time.

Some plugins such as llyrics do interfere because of some threading issues.

**Comment by fin-ger** [comment] 2016-02-14 15:06
I started rhythmbox in debug mode and was unable to cause a crash. Without debug mode I can still cause crashes.
I seems to be a Heisenbug...

**Comment by fossfreedom** [comment] 2016-02-14 15:08
ok - suggest use gdb 

 - https://wiki.ubuntu.com/Backtrace

**Comment by fin-ger** [comment] 2016-02-14 15:41
I am unable to cause a crash with gdb. After using gdb I cannot even cause a crash in rhythmbox without gdb.
I've got a gentoo linux.

rhythmbox-3.2.1 use-flags
- [X] cdr
- [ ] daap
- [X] dbus
- [ ] html
- [X] ipod
- [X] libnotify
- [X] libsecret
- [ ] lirc
- [ ] mtp
- [X] nsplugin
- [X] python
- [ ] python_targets_python3_3
- [X] python_targets_python3_4
- [X] udev
- [ ] upnp-av
- [ ] visualizer
- [ ] webkit
- [ ] zeitgeist

gtk+-3.16.7
python-3.4.3-r1

I will debug it when it crashes the next time. Compiling rhythmbox with debug symbols now.

**Comment by fossfreedom** [comment] 2016-02-14 15:45
an alternative way to get some-sort of tracing without recompiling is to run

rhythmbox -D alt

i.e. this will spit out in the terminal all the python print statements for all python modules starting with "alt" - most of the alternative-toolbar python modules are alt[something]

**Comment by fossfreedom** [comment] 2016-12-22 14:59
no feedback.  closing.

**Closed by fossfreedom** 2016-12-22 14:59 UTC
