### ISSUE TITLE
The CSD progress bar slider width is hardcoded.

### ISSUE THREAD

**Issue by me4oslav** [fossfreedom/alternative-toolbar#6] opened 2015-03-14 19:21 UTC
Which as you can imagine creates issue when the window is resized.
![screenshot from 2015-03-14 21 14 01](https://cloud.githubusercontent.com/assets/1658870/6653160/4cdc083e-ca8f-11e4-929b-0dd4dd5cf6e9.png)
![screenshot from 2015-03-14 21 14 13](https://cloud.githubusercontent.com/assets/1658870/6653159/4cdac2a8-ca8f-11e4-809d-ab4948ed6d22.png)
The first screenie is RB with minimum window width. I think the window size width wise is OK, but the progress bar should be longer. The second is with wider window and as you can see, the issue is very prominent.
We need it to be responsive and go longer when the user makes the window wider.

**Comment by me4oslav** [comment] 2015-03-14 19:39
Would really like to be able to add tags, though. ;P

**Comment by fossfreedom** [comment] 2015-03-14 20:13
Yep - came across this when first implemented this.

I'm not sure what the issue is.  The width is indeed hard-coded - altheaderbar.ui - search for "80" - you can see the width_chars and max_width_chars which are both 80

Even though the label has its "hexpand" set to True and its parent box "hexpand" is set to True, the bar doesnt expand to maximum width.

I was tempted to just hide the slider when nothing is playing - however when playing , the slider length is just the size of the song label - ok for long titled songs ... but obviously not when the song-title is just one or two characters!

BTW - what do you mean by tags?

**Comment by me4oslav** [comment] 2015-03-14 20:16
Tags as in Github tags. Like "bug", "won't fix" and so on and so forth.
Any way we can see that fixed? 'Cause it is quite the not so small issue.

**Comment by fossfreedom** [comment] 2015-03-14 20:20
I'll have a look - would like some help though if you or someone else has some thoughts on this.

**Comment by me4oslav** [comment] 2015-03-14 20:23
Oki-doki.
I have some more plans for that slider and CSD and the controls, that might not require you to fix that bug. Lemme do some personas, HIG reading, psyhology and wireframing and I will send it down to you.
Sorry for the design specific terms, sometimes I tend to get too pedantic.

**Comment by fossfreedom** [comment] 2015-03-21 21:57
closing in favour of #4 where this is really resolved.

**Closed by fossfreedom** 2015-03-21 21:57 UTC
Labels: enhancement, help wanted
